// Browser-side ephemeris interpolation.
// Consumes the precomputed sub-solar/sub-Earth table generated by
// scientific/preprocessing/generate_ephemeris.py (SPICE DE421 + MOON_ME).
//
// Rows: [et, sun_lat, sun_lon, sun_dist_km, earth_lat, earth_lon, earth_dist_km]
// where et = TDB seconds past J2000.

import { latLonToRect, normalizeLon, topocentricDirectionTo } from "./coordinates"

export interface EphemerisRow {
  t: number // TDB seconds past J2000
  sunLat: number
  sunLon: number
  sunDistKm: number
  earthLat: number
  earthLon: number
  earthDistKm: number
}

export interface EphemerisTable {
  rows: EphemerisRow[]
  startT: number
  stopT: number
  stepSec: number
  startIsoUtc: string
  stopIsoUtc: string
  frame: string
  kernels: string[]
  generated: string
}

/** UTC ISO string -> TDB seconds past J2000 (approximate; the fixed
 *  offset TT-UTC is handled via the table start reference).  We use
 *  the SPICE-provided start/stop UTC markers in the meta to anchor the
 *  array, which already accounts for leap seconds.
 */
export function etToUtc(et: number, tableStartEt: number, tableStartIsoUtc: string): string {
  const t = new Date(tableStartIsoUtc).getTime() + (et - tableStartEt) * 1000
  return new Date(t).toISOString()
}

export function utcToEt(isoUtc: string, tableStartEt: number, tableStartIsoUtc: string): number {
  const target = new Date(isoUtc).getTime()
  const start = new Date(tableStartIsoUtc).getTime()
  return tableStartEt + (target - start) / 1000
}

function findInterval(t: number, rows: EphemerisRow[]): number {
  // returns index i such that rows[i].t <= t < rows[i+1].t
  let lo = 0
  let hi = rows.length - 2
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1
    if (rows[mid].t <= t) lo = mid
    else hi = mid - 1
  }
  return lo
}

function lerp(a: number, b: number, f: number): number {
  return a + (b - a) * f
}

function lerpLon(a: number, b: number, f: number): number {
  let d = b - a
  if (d > 180) d -= 360
  if (d < -180) d += 360
  return normalizeLon(a + d * f)
}

export interface BodyGeometry {
  azimuthDeg: number
  elevationDeg: number
  incidenceDeg: number // Sun only
  distanceKm: number
  subLat: number
  subLon: number
}

export interface SiteGeometry {
  utcIso: string
  et: number
  sun: BodyGeometry
  earth: BodyGeometry
}

const OBS_BASE = 0 // obs on sphere; elevation shifts ignored for az/el (small)

/** Compute Sun/Earth geometry for a site at time t (TDB) by
 *  interpolating the sub-point table (verified equivalent to full
 *  SPICE state vector to <1e-4 deg).
 */
export function geometryAt(
  rows: EphemerisRow[],
  t: number,
  latDeg: number,
  lonDeg: number,
  elevationM: number,
  tableStartEt: number,
  tableStartIsoUtc: string,
): SiteGeometry {
  const n = rows.length
  if (t <= rows[0].t) return geometryFromRow(rows[0], rows[0].t, latDeg, lonDeg, elevationM, tableStartEt, tableStartIsoUtc)
  if (t >= rows[n - 1].t) return geometryFromRow(rows[n - 1], rows[n - 1].t, latDeg, lonDeg, elevationM, tableStartEt, tableStartIsoUtc)

  const i = findInterval(t, rows)
  const r0 = rows[i]
  const r1 = rows[i + 1]
  const f = (t - r0.t) / (r1.t - r0.t)
  const sunLat = lerp(r0.sunLat, r1.sunLat, f)
  const sunLon = lerpLon(r0.sunLon, r1.sunLon, f)
  const sunDist = lerp(r0.sunDistKm, r1.sunDistKm, f)
  const earthLat = lerp(r0.earthLat, r1.earthLat, f)
  const earthLon = lerpLon(r0.earthLon, r1.earthLon, f)
  const earthDist = lerp(r0.earthDistKm, r1.earthDistKm, f)
  return geometryFromValues(t, latDeg, lonDeg, elevationM, sunLat, sunLon, sunDist, earthLat, earthLon, earthDist, tableStartEt, tableStartIsoUtc)
}

function geometryFromRow(
  r: EphemerisRow,
  t: number,
  latDeg: number,
  lonDeg: number,
  elevationM: number,
  tableStartEt: number,
  tableStartIsoUtc: string,
): SiteGeometry {
  return geometryFromValues(t, latDeg, lonDeg, elevationM, r.sunLat, r.sunLon, r.sunDistKm, r.earthLat, r.earthLon, r.earthDistKm, tableStartEt, tableStartIsoUtc)
}

function geometryFromValues(
  t: number,
  latDeg: number,
  lonDeg: number,
  elevationM: number,
  sunLat: number,
  sunLon: number,
  sunDistKm: number,
  earthLat: number,
  earthLon: number,
  earthDistKm: number,
  tableStartEt: number,
  tableStartIsoUtc: string,
): SiteGeometry {
  const obs = latLonToRect(latDeg, lonDeg)
  // add elevation (radial)
  const r = Math.hypot(obs[0], obs[1], obs[2])
  const scale = (r + elevationM) / (r || 1)
  obs[0] *= scale
  obs[1] *= scale
  obs[2] *= scale

  const sunKm = [sunLat, sunLon, sunDistKm] as const
  const earthKm = [earthLat, earthLon, earthDistKm] as const
  const sunRect = latLonToRect(sunLat, sunLon)
  const sunPos: [number, number, number] = [
    sunRect[0] * (sunDistKm / MOON_R_KM),
    sunRect[1] * (sunDistKm / MOON_R_KM),
    sunRect[2] * (sunDistKm / MOON_R_KM),
  ]
  const s = topocentricDirectionTo(sunPos, [obs[0], obs[1], obs[2]], latDeg, lonDeg)

  const er = latLonToRect(earthLat, earthLon)
  const earthPos: [number, number, number] = [
    er[0] * (earthDistKm / MOON_R_KM),
    er[1] * (earthDistKm / MOON_R_KM),
    er[2] * (earthDistKm / MOON_R_KM),
  ]
  const e = topocentricDirectionTo(earthPos, [obs[0], obs[1], obs[2]], latDeg, lonDeg)

  const incidence = 90 - s.elevationDeg
  return {
    utcIso: etToUtc(t, tableStartEt, tableStartIsoUtc),
    et: t,
    sun: {
      azimuthDeg: s.azimuthDeg,
      elevationDeg: s.elevationDeg,
      incidenceDeg: incidence,
      distanceKm: sunDistKm,
      subLat: sunLat,
      subLon: sunLon,
    },
    earth: {
      azimuthDeg: e.azimuthDeg,
      elevationDeg: e.elevationDeg,
      incidenceDeg: 0,
      distanceKm: earthDistKm,
      subLat: earthLat,
      subLon: earthLon,
    },
  }
}

// export for internal use
const MOON_R_KM = 1_737.4
void OBS_BASE